import time
mvpMob = raw_input('MVP:')
mvpList = {'lhz_dun04':'1 Hour and 40 Minutes to 2 Hours and 10 Minutes left until respawn',
           'lhz_dun03':'1 Hour and 40 Minutes to 2 Hours and 10 Minutes left until respawn',
           'lou_dun03':'1 Hour and 57 Minutes to 2 Hours and 7 Minutes left until respawn',
           'moc_pryd06':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'ra_fild02':'4 Hours to 4 Hours and 10 Minutes left until respawn',
           'ra_fild03':'3 Hours to 3 Hours and 10 Minutes left until respawn',
           'ra_fild04':'5 Hours to 5 Hours and 10 Minutes left until respawn',
           've_fild01':'3 Hours to 3 Hours and 10 Minutes left until respawn',
           've_fild02':'6 Hours to 6 Hours and 10 Minutes left until respawn',
           'prt_maze03':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'bra_dun02':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'gl_chyard':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'gld_Dun04':'8 Hours to 8 Hours and 10 Minutes left until respawn',
           'abyss_03':'3 Hours to 3 Hours and 10 Minutes left until respawn',
           'gef_dun02':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'gld_dun02':'8 Hours to 8 Hours and 10 Minutes left until respawn',
           'gef_dun01':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'treasure02':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'gld_dun01':'8 Hours to 8 Hours and 10 Minutes left until respawn',
           'pay_fild11':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'gon_dun03':'1 Hour and 34 Minutes to 1 Hour and 44 Minutes left until respawn',
           'abbey02':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'xmas_fild01':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'ra_san05':'5 Hours to 5 Hours and 10 Minutes left until respawn',
           'dic_dun03':'2 Hours left until respawn',
           'prt_sewb4':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'mosk_dun03':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'thor_v03':'11 Hours to 11 Hours and 10 Minutes left until respawn',
           'ama_dun03':'1 Hour and 31 Minutes to 1 Hour and 41 Minutes left until respawn',
           'kh_dun02':'2 Hours to 3 Hours left until respawn',
           'xmas_dun02':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'iz_dun05':'2 Hours to 2 Hours and 30 Minutes left until respawn',
           'ayo_dun02':'7 Hours to 7 Hours and 10 Minutes left until respawn',
           'dew_dun01':'2 Hours left until respawn',
           'niflheim':'2 Hours and 13 Minutes left until respawn',
           'anthell02':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'gld_dun03':'8 Hours to 8 Hours and 10 Minutes left until respawn',
           'mjolnir_04':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'pay_dun04':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'gef_fild02':'24 Hours to 24 Hours and 10 Minutes left until respawn',
           'gef_fild14':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'gef_fild10':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'moc_pryd04':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'in_sphinx5':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'moc_fild17':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'dic_dun02':'2 Hours left until respawn',
           'ein_dun02':'2 Hours and 5 Minutes to 2 Hours and 15 Minutes left until respawn',
           'beach_dun':'5 Hours to 5 Hours and 10 Minutes left until respawn',
           'tur_dun04':'1 Hour to 1 Hour and 10 Minutes left until respawn',
           'odin_tem03':'8 Hours to 8 Hours and 10 Minutes left until respawn',
           'jupe_core':'2 Hours to 2 Hours and 10 Minutes left until respawn',
           'moc_fild22':'12 Hours to 13 Hours left until respawn',
           'lhz_dun02':'2 Hours to 2 Hours and 10 Minutes left until respawn'}
print(mvpList[mvpMob])
